# Generated by Django 5.0 on 2024-01-04 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_meal_favorited'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('calories', models.IntegerField()),
                ('carbs', models.IntegerField()),
                ('protein', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='bodydata',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.RemoveField(
            model_name='meal',
            name='food',
        ),
        migrations.AddField(
            model_name='meal',
            name='food',
            field=models.ManyToManyField(to='main_app.food'),
        ),
    ]
