# Generated by Django 5.0 on 2024-01-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_food_alter_bodydata_date_alter_meal_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='amount',
            new_name='servings',
        ),
        migrations.AddField(
            model_name='food',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
