# Generated by Django 5.0 on 2024-01-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_amount_meal_servings_food_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='amount',
            field=models.IntegerField(verbose_name='Weight(g)'),
        ),
    ]
