# Generated by Django 5.0 on 2024-01-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_profile_goalweight_alter_profile_initweight'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Alex'),
            preserve_default=False,
        ),
    ]
