# Generated by Django 5.0 on 2024-01-04 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AddField(
            model_name='profile',
            name='firstname',
            field=models.CharField(default='Alex', verbose_name='First Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='lastname',
            field=models.CharField(default='Keller', verbose_name='Last Name'),
            preserve_default=False,
        ),
    ]
