# Generated by Django 5.0 on 2024-01-05 21:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_profile_user_alter_profile_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='food',
        ),
        migrations.AddField(
            model_name='meal',
            name='foodname',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), default=['food1'], size=None),
            preserve_default=False,
        ),
    ]
