# Generated by Django 5.0 on 2024-01-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_remove_meal_food_meal_foodname'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealFoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servings', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='food',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='food',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='food',
            name='carbs',
        ),
        migrations.RemoveField(
            model_name='food',
            name='name',
        ),
        migrations.RemoveField(
            model_name='food',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='foodname',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='servings',
        ),
        migrations.AddField(
            model_name='meal',
            name='food',
            field=models.ManyToManyField(to='main_app.mealfooditem'),
        ),
    ]
