# Generated by Django 5.0 on 2024-01-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_mealfooditem_remove_food_amount_remove_food_calories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='Weight(g)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='calories',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='carbs',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='name',
            field=models.CharField(default='pie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='protein',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealfooditem',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='Weight(g)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealfooditem',
            name='calories',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealfooditem',
            name='carbs',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealfooditem',
            name='name',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealfooditem',
            name='protein',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
